most of functionality is in place, need to fix css and ingredient selector
nickschoey/Codeworks-mealee-client pull request #3
Opened 2018-08-14 15:32 UTC by gromoglasov

2018-08-15 07:31 UTC, nickschoey commented on src/containers/App/App.js
> +import 'antd/lib/date-picker/style/css';
This needs to be imported in App.css so it get applied over all the project. Already did on my branch

2018-08-15 07:31 UTC, nickschoey commented on src/containers/RecipeInputPage/css/index.css
> +.main {
we shouldn't be using classnames like body or main, they're too generic and we're prompt to collision as I realize now that I also named 'main' one of my classes

2018-08-15 07:31 UTC, nickschoey commented on src/containers/RecipeInputPage/css/index.css
> +p {
this 'p' is modifying the color of all the p tags across the whole project. Give it a class and modify it, not the whole selector

2018-08-15 07:31 UTC, nickschoey commented on src/containers/RecipeInputPage/css/index.css
> +
same as before for this button selector

2018-08-15 07:31 UTC, nickschoey commented on src/containers/RecipeInputPage/index.js
> +export default connect(mapStateToProps, mapDispatchToProps)(RecipeInputPage);
console.log... console.log's everywhere

2018-08-15 07:31 UTC, nickschoey commented on src/containers/RecipeInputPage/instructions-list.js
> +import React from 'react';
naming of the file. a component like this should be InstructionsList

2018-08-15 07:31 UTC, nickschoey commented on src/containers/RecipeInputPage/instructions-list.js
> +  renderListIteams = () => {
iteams -> items. We'll go crazy debugging an app because of typos

2018-08-15 07:31 UTC, nickschoey commented on src/containers/RecipeInputPage/quantity-input.js
> +import React from 'react';
same with the naming here

2018-08-15 07:31 UTC, nickschoey commented on src/containers/RecipeInputPage/recipe-form.js
> +      </div>
this is so hard to read. couldn't we use something like: 
`<RecipeName 
        name={this.props.recipe.name} 
        changeName={this.props.changeName}/>
<RecipeIngridientInput 
   name={this.props.recipe.name} 
    ingredientList={this.props.ingredientList} 
    addIngredient={this.props.addIngredient} 
    removeIngredient={this.props.removeIngredient}/>
<QuantityInput 
     measures={this.props.measures} 
     name={this.props.recipe.name} 
     ingredientList={this.props.ingredientList} 
     changeIngredientAmount={this.props.changeIngredientAmount}/>`

2018-08-15 07:31 UTC, nickschoey commented on src/containers/RecipeInputPage/recipe-form.js
> +      </div>
by the way, in some places you use 'ingridient' and in some others 'ingredient'

2018-08-16 14:29 UTC, arol requested changes

2018-08-16 14:29 UTC, arol commented on src/containers/App/App.js
> +        {/* <header className="App-header">
Remove commented code.

2018-08-16 14:29 UTC, arol commented on src/containers/RecipeInputPage/index.js
> +      measures: ['gramms', 'killos', 'litters', 'spoons', 'squirrels', 'bacteria']
WTF

2018-08-16 14:29 UTC, arol commented on src/containers/RecipeInputPage/index.js
> +    console.log(this.state);
Remove `console.logs`

2018-08-16 14:29 UTC, arol commented on src/containers/RecipeInputPage/quantity-input.js
> +  renderListIteams = () => {
Same, all iteams to items

2018-08-16 14:29 UTC, arol commented on src/containers/RecipeInputPage/quantity-input.js
> +    console.log(this.state.activeIngredientIndex);
Remove `console.logs`

2018-08-16 14:29 UTC, arol commented on src/containers/RecipeInputPage/recipe-form.js
> +import React from 'react';
File name, to CapitalCase.

2018-08-16 14:29 UTC, arol commented on src/containers/RecipeInputPage/recipe-review.js
> +  doNothing = () => {
remove this.

2018-08-16 14:29 UTC, arol commented on src/containers/RecipeInputPage/recipe-review.js
> +const mapDispatchToProps = (dispatch) => ({
remove this.

2018-08-16 14:29 UTC, arol commented on src/containers/RecipeInputPage/selected-ingredients.js
> +    console.log(this.props);
remove console.log

2018-08-16 14:29 UTC, arol commented on src/containers/RecipeInputPage/selected-ingredients.js
> +        <p className="ingredient__description">{ingredient.name}</p> </div>
closing div on next line

2018-08-16 14:29 UTC, arol commented on src/containers/RecipeInputPage/selected-ingredients.js
> +      return this.props.ingredientList.map((ingredient, i) => (<div
Start the `<div>` in the next line.

2018-08-16 14:29 UTC, arol commented on src/reducers/recipe-input.reducer.js
> +  let newDescription = [...state.description];
Agree with @nickschoey which approach to follow in the reducers.
Personally, I prefer to crate the new objects when I need them, often directly in the `return` statement.

2018-08-16 17:12 UTC, arol requested changes

2018-08-16 17:12 UTC, arol commented on src/containers/RecipeInputPage/ListOfInstructions.js
> +      return this.props.descriptionList.map((description, i) => (<li key={i} onClick={description => this.handleClick(i)}>{description}</li>));
`onClick={this.handleClick}` you're not using the description. You're creating a different function on every render call.

2018-08-16 17:12 UTC, arol commented on src/containers/RecipeInputPage/RecipeForm.js
> +import RecipeIngridientInput from './RecipeIngredient';
`RecipeIngredientInput`

2018-08-16 17:14 UTC, arol requested changes

2018-08-16 17:14 UTC, arol commented on src/containers/RecipeInputPage/RecipeForm.js
> +import RecipeIngridientInput from './RecipeIngredient';
Ingredient

2018-08-16 17:14 UTC, arol commented on src/containers/RecipeInputPage/RecipeIngredient.js
> +class RecipeIngridientInput extends React.Component {
Ingredient

2018-08-16 17:17 UTC, gromoglasov commented
fixed typos

2018-08-17 07:51 UTC, arol approved these changes

2018-08-17 11:20 UTC, merged